'use strict';

/**
 * Default Seed Questions for WorkRank "Đoán Hình – Đoán Nhạc" (Quiz Game V1)
 *
 * All questions use royalty-free/public domain images and royalty-free audio snippets.
 * Includes 10 Image Questions and 10 Music/Sound Questions.
 */
const DEFAULT_QUIZ_QUESTIONS = [
  // ── MODE 1: IMAGE QUESTIONS (10 câu) ──
  {
    type: 'IMAGE',
    category: 'Ẩm Thực & Đồ Uống',
    question: 'Hình ảnh sau đây là món thức uống truyền thống nổi tiếng nào của Việt Nam?',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    optionA: 'Cà phê phin sữa đá',
    optionB: 'Trà sen vàng',
    optionC: 'Matcha đá xay',
    optionD: 'Trà tắc xí muội',
    correctOption: 'A',
    explanation: 'Cà phê phin sữa đá là thức uống biểu tượng của văn hóa cà phê Việt Nam.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'IMAGE',
    category: 'Công Nghệ',
    question: 'Logo linh vật sau đây đại diện cho hệ điều hành mã nguồn mở nào?',
    imageUrl: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=600&auto=format&fit=crop&q=80',
    optionA: 'FreeBSD',
    optionB: 'Linux (Tux)',
    optionC: 'macOS',
    optionD: 'Solaris',
    correctOption: 'B',
    explanation: 'Chú chim cánh cụt Tux là linh vật chính thức của nhân hệ điều hành Linux.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'IMAGE',
    category: 'Ẩm Thực',
    question: 'Món ăn đặc sản đường phố Việt Nam xuất hiện trong hình là gì?',
    imageUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=600&auto=format&fit=crop&q=80',
    optionA: 'Bánh bao hấp',
    optionB: 'Bánh mì kẹp thịt giòn rụm',
    optionC: 'Bánh xèo miền Tây',
    optionD: 'Bánh cuốn nóng',
    correctOption: 'B',
    explanation: 'Bánh mì Việt Nam liên tục nằm trong top các món kẹp đường phố ngon nhất thế giới.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'IMAGE',
    category: 'Địa Danh & Kiến Trúc',
    question: 'Cây cầu dây văng hình cánh cung nổi tiếng này nằm ở thành phố nào của Việt Nam?',
    imageUrl: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=600&auto=format&fit=crop&q=80',
    optionA: 'Cầu Rồng (Đà Nẵng)',
    optionB: 'Cầu Long Biên (Hà Nội)',
    optionC: 'Cầu Ba Son (TP. Hồ Chí Minh)',
    optionD: 'Cầu Cần Thơ',
    correctOption: 'A',
    explanation: 'Cầu Rồng bắc qua sông Hàn tại Đà Nẵng, có khả năng phun lửa và nước vào cuối tuần.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'IMAGE',
    category: 'Văn Phòng & Năng Suất',
    question: 'Vật dụng văn phòng tiện ích trong hình dùng để làm gì?',
    imageUrl: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
    optionA: 'Kẹp bướm giữ tài liệu',
    optionB: 'Bút dạ quang đánh dấu',
    optionC: 'Bấm kim dập ghim',
    optionD: 'Băng dính hai mặt',
    correctOption: 'A',
    explanation: 'Kẹp bướm (binder clip) là vật dụng văn phòng phổ biến để kẹp xấp giấy tờ dày.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'IMAGE',
    category: 'Công Nghệ',
    question: 'Ngôn ngữ lập trình biểu tượng với chiếc cốc cà phê bốc khói là ngôn ngữ nào?',
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80',
    optionA: 'Python',
    optionB: 'Java',
    optionC: 'C#',
    optionD: 'Rust',
    correctOption: 'B',
    explanation: 'Java có logo kinh điển hình cốc cà phê nóng của Sun Microsystems / Oracle.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'IMAGE',
    category: 'Thiên Nhiên & Du Lịch',
    question: 'Di sản thiên nhiên thế giới nổi tiếng với hàng ngàn đảo đá vôi kỳ vĩ này là ở đâu?',
    imageUrl: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=600&auto=format&fit=crop&q=80',
    optionA: 'Vịnh Hạ Long (Quảng Ninh)',
    optionB: 'Đảo Phú Quốc (Kiên Giang)',
    optionC: 'Tràng An (Ninh Bình)',
    optionD: 'Hồ Ba Bể (Bắc Kạn)',
    correctOption: 'A',
    explanation: 'Vịnh Hạ Long là một trong những kỳ quan thiên nhiên thế giới được UNESCO công nhận.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'IMAGE',
    category: 'Ẩm Thực',
    question: 'Món nước với nước dùng thanh ngọt, bánh phở mềm và thịt bò/gà trong hình là gì?',
    imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&auto=format&fit=crop&q=80',
    optionA: 'Bún bò Huế',
    optionB: 'Phở truyền thống',
    optionC: 'Hủ tiếu Nam Vang',
    optionD: 'Bánh canh cua',
    correctOption: 'B',
    explanation: 'Phở là quốc hồn quốc túy của nền ẩm thực Việt Nam.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'IMAGE',
    category: 'Gaming & Đồ Họa',
    question: 'Thiết bị ngoại vi hỗ trợ chơi game và làm việc đồ họa chuyên nghiệp trong ảnh là gì?',
    imageUrl: 'https://images.unsplash.com/photo-1612287233207-62287955c453?w=600&auto=format&fit=crop&q=80',
    optionA: 'Tay cầm chơi game (Gamepad/Controller)',
    optionB: 'Kính thực tế ảo VR',
    optionC: 'Bàn phím công thái học',
    optionD: 'Chuột trackball',
    correctOption: 'A',
    explanation: 'Tay cầm chơi game không dây hỗ trợ điều khiển linh hoạt trong các tựa game.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'IMAGE',
    category: 'Khoa Học & Đời Sống',
    question: 'Thiết bị dùng để quan sát những vật thể siêu vi không thể nhìn bằng mắt thường là gì?',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&auto=format&fit=crop&q=80',
    optionA: 'Kính thiên văn',
    optionB: 'Kính hiển vi',
    optionC: 'Ống nhòm tầm xa',
    optionD: 'Kính phóng đại lúp',
    correctOption: 'B',
    explanation: 'Kính hiển vi (Microscope) là công cụ nền tảng trong nghiên cứu sinh học và y tế.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },

  // ── MODE 2: MUSIC / SOUND QUESTIONS (10 câu) ──
  {
    type: 'MUSIC',
    category: 'Âm Nhạc Cổ Điển',
    question: 'Đoạn giai điệu piano bất hủ này là tác phẩm nổi tiếng nào của thiên tài Beethoven?',
    audioUrl: 'https://cdn.freesound.org/previews/573/573577_11861866-lq.mp3',
    optionA: 'Für Elise (Thư gửi Elise)',
    optionB: 'Moonlight Sonata (Bản giao hưởng Ánh Trăng)',
    optionC: 'Bản giao hưởng số 5 (Định Mệnh)',
    optionD: 'Ode to Joy (Khải Hoàn Ca)',
    correctOption: 'A',
    explanation: 'Für Elise cung La thứ (WoO 59) là một trong những khúc độc tấu piano nổi tiếng nhất của Beethoven.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'MUSIC',
    category: 'Retro Gaming',
    question: 'Giai điệu 8-bit chiptune vui nhộn sau đây là nhạc nền của tựa game kinh điển nào?',
    audioUrl: 'https://cdn.freesound.org/previews/458/458867_7527632-lq.mp3',
    optionA: 'Super Mario Bros (Overworld Theme)',
    optionB: 'Tetris (Korobeiniki)',
    optionC: 'Pac-Man Arcade',
    optionD: 'Contra',
    correctOption: 'A',
    explanation: 'Giai điệu huyền thoại của Koji Kondo sáng tác cho tựa game Super Mario Bros năm 1985.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'MUSIC',
    category: 'Nhạc Cụ Dân Tộc',
    question: 'Âm sắc thanh thoát, vang ngân đặc trưng trong đoạn nhạc được phát ra từ nhạc cụ nào?',
    audioUrl: 'https://cdn.freesound.org/previews/612/612085_5674468-lq.mp3',
    optionA: 'Đàn Tranh (Đàn thập lục)',
    optionB: 'Đàn Bầu (Độc huyền cầm)',
    optionC: 'Đàn T\'rưng Tây Nguyên',
    optionD: 'Sáo trúc',
    correctOption: 'A',
    explanation: 'Đàn Tranh có âm sắc trong trẻo, réo rắt, thường dùng trong âm nhạc dân gian và thính phòng.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'MUSIC',
    category: 'Âm Thanh Đời Sống',
    question: 'Hiệu ứng âm thanh ấm áp, êm dịu này là tiếng của hiện tượng tự nhiên nào?',
    audioUrl: 'https://cdn.freesound.org/previews/518/518858_11326442-lq.mp3',
    optionA: 'Tiếng mưa rơi tí tách trên mái hiên',
    optionB: 'Tiếng sóng biển vỗ bờ cát',
    optionC: 'Tiếng lửa reo tí tách trong lò sưởi',
    optionD: 'Tiếng suối chảy róc rách trong rừng',
    correctOption: 'A',
    explanation: 'Tiếng mưa rơi (White Noise/Rain Sound) thường được dùng để thư giãn và tập trung làm việc.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'MUSIC',
    category: 'Âm Nhạc Cổ Điển',
    question: 'Giai điệu vĩ cầm (Violin) cao trào, rộn rã này thuộc chương "Mùa Xuân" trong bộ tứ tấu nào?',
    audioUrl: 'https://cdn.freesound.org/previews/235/235868_2538031-lq.mp3',
    optionA: 'Bốn Mùa (The Four Seasons - Vivaldi)',
    optionB: 'Hồ Thiên Nga (Swan Lake - Tchaikovsky)',
    optionC: 'Canon in D (Pachelbel)',
    optionD: 'Dòng sông Danube xanh (Strauss II)',
    correctOption: 'A',
    explanation: 'Bộ 4 bản concerto "Le quattro stagioni" (The Four Seasons) của nhà soạn nhạc Antonio Vivaldi.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'MUSIC',
    category: 'Thư Giãn & Lofi',
    question: 'Dòng nhạc thư giãn với tiết tấu chậm rãi, kết hợp tiếng vinyl và hợp âm jazz ấm áp này là gì?',
    audioUrl: 'https://cdn.freesound.org/previews/530/530415_11565147-lq.mp3',
    optionA: 'Lofi Hip Hop (Chill Beats)',
    optionB: 'Hardstyle EDM',
    optionC: 'Heavy Metal',
    optionD: 'Psychedelic Rock',
    correctOption: 'A',
    explanation: 'Lofi Hip Hop là thể loại nhạc ưa thích của dân văn phòng và coder khi cần tập trung cao độ.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'MUSIC',
    category: 'Âm Nhạc Cổ Điển',
    question: 'Giai điệu du dương quen thuộc thường được phát trong các lễ cưới trang trọng là bản nhạc nào?',
    audioUrl: 'https://cdn.freesound.org/previews/387/387186_7142407-lq.mp3',
    optionA: 'Canon in D Major (Johann Pachelbel)',
    optionB: 'Air on the G String (J.S. Bach)',
    optionC: 'Clair de Lune (Claude Debussy)',
    optionD: 'Nocturne Op. 9 No. 2 (Chopin)',
    correctOption: 'A',
    explanation: 'Canon in D của Pachelbel là một trong những bản nhạc thính phòng phổ biến nhất mọi thời đại.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'MUSIC',
    category: 'Nhạc Điện Tử',
    question: 'Nhịp trống điện tử "Four-on-the-floor" (128 BPM) dồn dập đặc trưng cho thể loại âm nhạc nào?',
    audioUrl: 'https://cdn.freesound.org/previews/495/495574_10672023-lq.mp3',
    optionA: 'EDM / Progressive House',
    optionB: 'Country Folk',
    optionC: 'Acoustic Ballad',
    optionD: 'Jazz Bossa Nova',
    correctOption: 'A',
    explanation: 'House/EDM với cấu trúc bassline 4 nhịp là dòng nhạc sôi động tạo năng lượng tại các lễ hội âm nhạc.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'MUSIC',
    category: 'Văn Hóa Dân Gian',
    question: 'Âm vang trầm hùng, ngân vang như tiếng sấm của nhạc cụ gõ Tây Nguyên này là gì?',
    audioUrl: 'https://cdn.freesound.org/previews/320/320655_5260872-lq.mp3',
    optionA: 'Cồng Chiêng Tây Nguyên',
    optionB: 'Trống Đồng Đông Sơn',
    optionC: 'Khèn Bè',
    optionD: 'Trống Cơm',
    correctOption: 'A',
    explanation: 'Không gian văn hóa Cồng chiêng Tây Nguyên là Di sản phi vật thể đại diện của nhân loại.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
  {
    type: 'MUSIC',
    category: 'Âm Thanh & Công Nghệ',
    question: 'Hiệu ứng âm thanh tăng dần tông báo hiệu chiến thắng trong game này gọi là gì?',
    audioUrl: 'https://cdn.freesound.org/previews/270/270404_5123851-lq.mp3',
    optionA: 'Fanfare / Victory Jingle',
    optionB: 'Game Over Buzzer',
    optionC: 'Low Battery Beep',
    optionD: 'Glitch Distortion',
    correctOption: 'A',
    explanation: 'Victory Fanfare là giai điệu báo hiệu người chơi vượt qua ải hoặc chiến thắng trận đấu.',
    timeLimit: 10,
    points: 1000,
    isActive: true,
  },
];

module.exports = {
  DEFAULT_QUIZ_QUESTIONS,
};
